### ISSUE TITLE
Unable to open aplication

### ISSUE THREAD

**Issue by tabytac** [jealouscloud/linerider-advanced#46]
Am running windows 10 with admin rights and nothing happens when running line rider 1.02, 1.03 or 10.4.

 Have tried with admin rights and without and have extracted in documents vs program files to see if there was a difference. 

Microsoft net. 4.6 wont install as I already have a newer version installed on my pc.

Task manager shows the program running for about a second and just disappears and there is never an error message. Just nothing. Thanks for the help and for keeping this game alive!

**Comment by jealouscloud** [comment]
I'm not sure, do you have the latest graphics drivers for your system?

**Comment by tabytac** [comment]
Just updated my graphics drivers (have an mx150 mobile GPU) and tried all of the steps that I mentioned above and still will not run. Confused about this error and I dont know what can be done to fix this easily.
