### ISSUE TITLE
Bug: Playback speed not updated using spacebar

### ISSUE THREAD

**Issue by joeabolt** [jealouscloud/linerider-advanced#51]
### Observed Behavior
After changing playback speed, using the spacebar to start/stop will not use the newest playback speed, but clicking the "play" button will.

### Expected Behavior
Any method of starting or stopping playback will use the newest playback speed.

**Comment by jealouscloud** [comment]
I'm unable to see the bug as you've reported it. However, I was able to replicate by pausing, increasing the playback speed, and actually clicking the play button.

**Comment by jealouscloud** [comment]
Marking as closed, fixed in 5698946
