### ISSUE TITLE
LRA Black Screen

### ISSUE THREAD

**Issue by pmehlb** [jealouscloud/linerider-advanced#53]
Despite already having installed .NET 4.6 (and later versions) installed (see [this image](https://i.imgur.com/ZDiwKpb.png) as proof), LRA just shows a [black screen](https://i.imgur.com/jplMFe7.png)...

I'm using linerider104.zip, so the most updated version on the website, and [these are the files](https://i.imgur.com/Dmg99em.png) I have in the folder.

Any ideas? I'm going to try and figure out how to build this, I'm getting dependency errors despite download all the files used for building.

**Comment by pmehlb** [comment]
I'm going to download the newest GeForce driver for me and see if it makes any difference, I should have thought of this before posting, sorry.

**Comment by jealouscloud** [comment]
If you are having trouble compiling from source it's likely you haven't downloaded lra-gwen appropriately. From the command line, you need to ```git clone --recursive (whatever the lra git link is```. The alternative is downloading lra-git manually from my repo and then plopping it in the `lib` directory. 

If new drivers do not fix the issue it is very likely msaa is unsupported on your system, or you have a custom as setting configured with your drivers (noted in #10)
If you can work out compiling from source and those things don't help I can guide on trying to disable msaa

**Comment by pmehlb** [comment]
Upon installing an updated driver and restarting, all is well. Thanks, sorry I'm an idiot lol
