### ISSUE TITLE
Line extension(red) 

### ISSUE THREAD

**Issue by Crownbeach** [jealouscloud/linerider-advanced#60]
When i make a gravitywell and click to show line hitboxes the lines red extension never shows.

**Comment by jealouscloud** [comment]
This project is no longer maintained.

**Comment by Crownbeach** [comment]
oh thats unfortunet for me. is it time consuming to fix it?

**Comment by jealouscloud** [comment]
I don't think I ever put line extensions in an official version, but a debug flag enables it when you press C.

https://github.com/jealouscloud/linerider-advanced/blob/597b3d325e436a62b600bd6077acffd71ab7e989/src/MainWindow.cs#L1

Uncommenting this line so it's just
`#define debuggrid`
And then compiling the game will enable the feature. It will also display the actual physics grid.
