### ISSUE TITLE
unable to start?

### ISSUE THREAD

**Issue by zxddd2** [jealouscloud/linerider-advanced#62]
Please consult the download and unzip, win10. But there is no response after double clicking, unable to start?

**Comment by zxddd2** [comment]
unable to start?

**Comment by zxddd2** [comment]
Please consult the download and unzip, win10. But there is no response after double clicking, unable to start?

**Comment by jealouscloud** [comment]
Windows

If you can't run the application, you probably need to install [.net 4.6](https://www.microsoft.com/en-us/download/details.aspx?id=48130) which is a requirement for running LRA.
